### ISSUE TITLE
Confusion about the internals of ProducerSink

### ISSUE THREAD

**Issue by benjumanji** [monix/monix-kafka#36]
I'd like to understand why we are suggesting an io scheduler and using the blocking version of send for the producer. I guess there must be a reason to prefer this over creating tasks that correspond to the completion of each send. Is it a performance thing? I think even if you didn't want to create a task per send you could happily create a callback that incremented a batch size and completed a single task with either all the metadata / exceptions rolled up into it.

What am I missing?

**Comment by benjumanji** [comment]
Ok, having read some more now I am even more confused. In the sink we are using our _own_ version of the producer, which does use the async apis. Why do we need an io scheduler for that? What's wrong with the regular forkjoin? There is zero blocking that I can see?

**Comment by Avasil** [comment]
Hi @benjumanji - sorry for the delay.

The blocking part is actually waiting for Kafka's callback to complete and it's mostly I/O bound

**Comment by benjumanji** [comment]
Sorry if I being dense, but where in the code that do we block waiting for the callback?

**Comment by Avasil** [comment]
In [KafkaProducer.send](https://github.com/monix/monix-kafka/blob/master/kafka-1.0.x/src/main/scala/monix/kafka/KafkaProducer.scala#L68) we construct `Task` whose completion is [signaled with callback from Kafka](https://github.com/monix/monix-kafka/blob/master/kafka-1.0.x/src/main/scala/monix/kafka/KafkaProducer.scala#L93) meaning that `Task` will run until it hears back from Kafka.

It's using low-level Monix functions so it might be harder to see

**Comment by benjumanji** [comment]
No, I totally see that. I wouldn't have thought however that the length of time that you wait to signal completion for a task has no bearing on the choice of scheduler. The actual work being dispatched by the scheduler is the same whether you get called back 10 microseconds or 10 minutes. No thread is blocked in the underlying threadpool. The only reason I would have thought to have a separate cached threadpool over a shared forkjoin pool would be if the _actual_ tasks themselves contain IO. In the consumer case, that's obviously true because there is no async poll function (there is no variant that takes a callback). In the producer case that's not true at all.

**Comment by leandrob13** [comment]
@benjumanji @Avasil I can tell you we just found out the hard way about this issue. I can lay it down so you could help me understand if it is related.

When having bad config for TLS, like setting the protocol to PLAINTEXT, the publishing of a message crashes our app with OOM. When testing with 10 concurrent users, we could see in visual vm 9 threads blocked and one alive before the crash. We are using the Scheduler.io.

I am strongly leaning forward into addressing this as soon as we can.

**Comment by benjumanji** [comment]
@leandrob13 I don't think this question is directly related, but if you haven't gotten to the bottom of your problem hit me up on keybase, I'd love to help if you have a sample application etc.

**Comment by leandrob13** [comment]
@benjumanji @Avasil It turns out we came across a bug hard to catch: https://issues.apache.org/jira/browse/KAFKA-4090

It sees it has never been addressed, it is an issue in the kafka client and has nothing to do with monix-kafka. I didn't really get why this happens and looking into the client's code does not help.

With the aide of visual vm, this issue helped me understand part of this discussion. In our case for 10 concurrent users we saw the 10 threads of `Scheduler.io()`, 9 of them were blocked waiting for the first one to finish its task (which it never did because of the error above). So it is the `KafkaProducer` that is blocking the rest of the threads in execution even though the [kafka client's producer is being called async](https://github.com/monix/monix-kafka/blob/master/kafka-1.0.x/src/main/scala/monix/kafka/KafkaProducer.scala#L86).

Taking into consideration cases under a heavy load and knowing that the `Scheduler.io()` is unbounded, we would want to release those threads as fast as we can, not block them while waiting for a previous send to finish in order to free the resource.

Is that a correct understanding? Is there some consideration I am missing?

**Comment by benjumanji** [comment]
That bug is fun, I wander if they'd accept a special case on the plaintext listener that looks for the inital ssl handshake and explodes a bit more gracefully. As to the current discussion:

The only reason you ever want more java threads than you have cpu threads is that some threads will be idle, therefore to maximize cpu productivity you schedule enough threads that you always have some that have some work to do while some are idle. In the case of the producer it has some blackbox eventloop / pool that it uses for doing network ops and should _only_ invoke the callback when there is productive work to be done (i.e. no sleeping / idling / blocking) therefore the default forkjoin scheduler should be right one.

In your case, were the threads blocked or idle? If they were blocked that's a problem. If they were just idle because no work could be scheduled on them because of program semantics (no sends completed etc) then that's fine.

**Comment by leandrob13** [comment]
@benjumanji sorry to take so much to respond. Yes, the threads were blocked waiting for the problematic first thread to finish (which never did and killed the app with OOM).
